config/routes.rb
Rails.application.routes.draw do
  resources :customers
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    @customer = Customer.new
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customers_path, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :index }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customers_path, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:firstname, :lastname, :gender, :email, :date_of_birth, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/customers/_customer_modal.html.erb
<!-- Customer form Modal -->
<div class="modal fade" id="customer-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/customers/_form.html.erb
<%= form_with(model: @customer, local: true) do |form| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this @customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class=form-group>
    <%= form.label :firstname %>
    <%= form.text_field :firstname, class: "form-control" %>
  </div>

  <div class=form-group>
    <%= form.label :lastname %>
    <%= form.text_field :lastname, class: "form-control" %>
  </div>

  <div class=form-group>
    <%= form.label :gender %>
    <%= form.text_field :gender, class: "form-control" %>
  </div>

  <div class=form-group>
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class=form-group>
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth %>
  </div>

  <div class=form-group>
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<div id="customers">
    <div class="container">
        <div class="row">
            <%= render "shared/sidebar" %>
            <div class="col-md-9 canvas">
                <div class="title-section">
                    <div class="d-flex justify-content-between">
                      <h3>Customers</h3>
                      <p id="notice"><%= notice %></p>
                      <button type="button" class="btn btn-custom" data-toggle="modal" data-target="#customer-form">New Customer</button>
                    </div>
                </div>

                <div class="customer-list">
                    <div class="rolw">
                      <table class="table table-borderless">
                        <thead>
                          <tr>
                            <th scope="col">Customer</th>
                            <th scope="col">Email</th>
                            <th scope="col">Gender</th>
                            <th scope="col">DOB</th>
                            <th>Phone</th>
                            <th cope="col" colspan="3">Action</th>
                          </tr>
                        </thead>

                        <div class="customer-llist-body">
                          <tbody class="customer-list-body">
                            <% @customers.each do |customer| %>
                              <tr>
                                <td class="name-space"><div class="avatar"></div><div class="name"><%= customer.firstname + " " + customer.lastname %></div></td>
                                <td><%= customer.email %></td>
                                <td><span class="badge badge-success"><%= customer.gender %></span></td>
                                <td><%= customer.date_of_birth %></td>
                                <td><%= customer.phone %></td>
                                <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
                                <td><%= link_to 'Delete', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                              </tr>
                            <% end %>
                          </tbody>
                        </div>
                      </table>
                    </div>
                </div>
            </div>
            <%= render "customer_modal" %>
        </div>
    </div>
</div>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @customer.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @customer.lastname %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @customer.gender %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>date_of_birth:</strong>
  <%= @customer.date_of_birth %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/home/index.html.erb
<div id="dashboard">
    <div class="container">
        <div class="row">
            <%= render "shared/sidebar" %>
            <div class="col-md-9 canvas">
                <div class="title-section">
                    <h3>Recent Activity</h3>
                </div>
                
                <div class="container">
                    <div class="row">
                        <%# recent recent_customers %>
                        <%= render "shared/recent_customers" %>
                        
                        <%# recent services %>
                        <%= render "shared/recent_services" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zoodle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_activity_analytics.html.erb
<div class="col-md-12 activity-analytics">
    <div class="header-section">
        <h3>Recent Customers</h3>
    </div>
    <div class="list-section">
        <ul class="list-group">
            <% 5.times do %>
                <%= render "shared/customer_item" %>
            <% end %>
        </ul>
    </div>
</div>

app/views/shared/_customer_item.html.erb
<li class="list-group-item">
    <div class="avatar">
    </div>

    <div class="name">
        Cras justo odio
    </div>
</li>

app/views/shared/_recent_customers.html.erb
<div class="col-md-5 recent-customers">
    <div class="header-section">
        <h3>Recent Customers</h3>
    </div>
    <div class="list-section">
        <ul class="list-group">
            <% 5.times do %>
                <%= render "shared/customer_item" %>
            <% end %>
        </ul>
    </div>
</div>

app/views/shared/_recent_services.html.erb
<div class="col-md-7 recent-services">
    <div class="header-section">
        <h3>Recent Servicess</h3>
    </div>
    <div class="list-section">
        <ul class="list-group">
            <% 5.times do %>
                <%= render "shared/service_item" %>
            <% end %>
        </ul>
    </div>
</div>

app/views/shared/_service_item.html.erb
<li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
    <p><span class="badge badge-pill badge-warning service-badge lefted">Warning</span>Service lorem</p>
    <span class="badge badge-custom badge-pill">14</span>
</li>

app/views/shared/_sidebar.html.erb
<div class="col-md-3  col align-self-center" id="dashboard-sidebar">
    <div class="logo-header">
        <h1>zoodle</h1>
    </div>

    <div class="profile-header">
        <h2>Zombie Centreal</h2>
        <a href="">Edit Profile</a>
    </div>

    <div class="dashboard-tools">
        <div class="list-group">
            <a href="/" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">Dashboard</a>
            <a href="/customers" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">Customers <span class="badge badge-custom badge-pill">14</span></a>
            <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">Services <span class="badge badge-custom badge-pill">14</span></a>
            <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">Users <span class="badge badge-custom badge-pill">14</span></a>
        </div>
    </div>

    <div class="sidebar-footer">
        <p>2019 copywrite All Rights Reserved</p>
    </div>
</div>